"""Add price column to donuts table

Revision ID: 34e204fbcdda
Revises: a9bf50e367a7
Create Date: 2024-06-16 19:32:36.683235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34e204fbcdda'
down_revision: Union[str, None] = 'a9bf50e367a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donuts', sa.Column('price', sa.Integer(), nullable=True))
    op.add_column('donuts', sa.Column('image_filename', sa.String(), nullable=True))
    op.create_index(op.f('ix_donuts_description'), 'donuts', ['description'], unique=False)
    op.drop_column('donuts', 'image_path')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donuts', sa.Column('image_path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_donuts_description'), table_name='donuts')
    op.drop_column('donuts', 'image_filename')
    op.drop_column('donuts', 'price')
    # ### end Alembic commands ###
