"""Initial migration

Revision ID: a9bf50e367a7
Revises: 
Create Date: 2024-06-14 02:46:08.042534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bf50e367a7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('donuts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_donuts_id'), 'donuts', ['id'], unique=False)
    op.create_index(op.f('ix_donuts_name'), 'donuts', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_donuts_name'), table_name='donuts')
    op.drop_index(op.f('ix_donuts_id'), table_name='donuts')
    op.drop_table('donuts')
    # ### end Alembic commands ###
